services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  dotnet-app:
    build:
      context: ./Co.WebApi
      dockerfile: Dockerfile
    container_name: dotnet-app
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=123456;Database=mydatabase
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
